### PR TITLE
Support proxy request to by pass CORS in flutter web

### PR DESCRIPTION
**Pull request by ductranminh**
There is a [CORS issue](https://help.mixpanel.com/hc/en-us/articles/115004511086-CORS-errors) when using MixPanel in flutter web 
I want to use a proxy to bypass this error on flutter web client by using https://github.com/spenibus/cors-everywhere-firefox-addon
The url format is `https://cors-anywhere.herokuapp.com/api.mixpanel.com/track/?data=data&verbose=1`
If there is no proxy, it just works normally on android & iOS

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi @ductranminh! Thanks for this PR. Could you fix the conflicts? I'll review it then. For what I've already seen, it looks good to me.

**Comment by robertohuertasm** [comment]
@ductranminh, @bookbotdev do you still need this feature? I cannot push to your branch, so I cannot resolve the issue myself. Can you look into the merge conflicts? Otherwise, we'll proceed to close this PR :(

**Comment by ductranminh** [comment]
Hi @robertohuertasm, I just merge it. Sorry I missed your previous comment.

**Review by robertohuertasm — APPROVED** [review]

**Comment by robertohuertasm** [comment]
@ductranminh, thanks for your contribution! ❤️

**Pull request merged**
